apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kubecrate-local-selfsigned
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: kubecrate
    kubecrate.io/workload-category: platform-services
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cratecheck-local-ca
  namespace: core-cert-manager
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: kubecrate
    kubecrate.io/workload-category: platform-services
spec:
  isCA: true
  commonName: kubecrate local CA
  secretName: cratecheck-local-ca
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: kubecrate-local-selfsigned
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kubecrate-local-ca
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: kubecrate
    kubecrate.io/workload-category: platform-services
spec:
  ca:
    secretName: cratecheck-local-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cratecheck-tls
  namespace: cratecheck
  labels:
    app.kubernetes.io/name: cert-manager
    app.kubernetes.io/part-of: kubecrate
    kubecrate.io/workload-category: platform-services
spec:
  commonName: cratecheck.local
  dnsNames:
    - cratecheck.local
  secretName: cratecheck-tls
  duration: 2160h
  renewBefore: 360h
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: kubecrate-local-ca
