apiVersion: v1
kind: Namespace
metadata:
  name: kyverno-smoke-allowed
  labels:
    kubecrate.io/validated: "true"
    app.kubernetes.io/name: kyverno-smoke-allowed
    app.kubernetes.io/part-of: kubecrate
    kubecrate.io/workload-category: application-services
    kubecrate.io/smoke-test: kyverno
