apiVersion: v1
kind: Secret
metadata:
  name: eso-smoke-source
  namespace: kubecrate-system
  labels:
    app.kubernetes.io/name: eso-smoke-source
    app.kubernetes.io/part-of: kubecrate
    kubecrate.io/workload-category: platform-services
    kubecrate.io/smoke-test: external-secrets-operator
stringData:
  smoke-test: kubecrate-eso-smoke-ok
