apiVersion: v1
kind: Service
metadata:
  name: cratecheck
  namespace: cratecheck
  labels:
    app.kubernetes.io/name: cratecheck
    app.kubernetes.io/part-of: kubecrate
spec:
  selector:
    app.kubernetes.io/name: cratecheck
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
