apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: envoy-smoke-cratecheck
  namespace: cratecheck
  labels:
    app.kubernetes.io/name: envoy-gateway
    app.kubernetes.io/part-of: kubecrate
    kubecrate.io/workload-category: platform-services
    kubecrate.io/smoke-test: envoy-gateway
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: kubecrate-envoy-smoke
      namespace: core-envoy-gateway
      sectionName: http
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: kubecrate-envoy-smoke
      namespace: core-envoy-gateway
      sectionName: https
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: cratecheck
          port: 8080
